version: "2"
services:
  # ----------------------------------------
  # Broker
  # ----------------------------------------

  rabbit:
    hostname: "rabbit"
    build: services/rabbit
    expose:
      - "5672"
    command: "rabbitmq-server"
    ports:
      # Interfase Administrativa
      - "15672:15672"
      # Puerto de MQTT/ws
      - "15675:15675"
      # MQTT
      - "11883:1883"
    restart: unless_stopped

  hivemq_client:
    hostname: hivemq_client
    build: services/hivemq_client
    expose:
      - 80

  # ----------------------------------------
  # Aplicación Web
  # ----------------------------------------

  flask:
    build: services/flask
    hostname: "flask"
    depends_on:
      - rabbit
    restart: unless_stopped
    # env_file:
    #   - ./docker.env
  # ----------------------------------------
  # Servidor frontera
  # ----------------------------------------
  #
  #
  # ----------------------------------------
  nginx:
    build: services/nginx
    hostname: "nginx"
    ports:
      - "80:80"
    depends_on:
      - flask
      - jupyter
    restart: unless_stopped

  jupyter:
    build: services/jupyter
    restart: unless_stopped

